### ISSUE TITLE
Code for training and testing mini/tiered-ImageNet datasets

### ISSUE THREAD

**Issue by khoiucd** [peymanbateni/simple-cnaps#1]
Very great work! I am interested in your results on mini/tiered-ImageNet datasets. Can you share some instructions for training and testing mini/tiered-ImageNet datasets? Thank you.

**Comment by peymanbateni** [comment]
Hi there, apologies for the late reply! It seems like the notification for the issue was not received.

Absolutely! I'll clean up the code for training and testing on mini/tiered-ImageNet and upload it over the weekend. I do hope that it's not very late :)

**Comment by khoiucd** [comment]
Thank you for your kind reply! I would love to see the code soon!

**Comment by peymanbateni** [comment]
Sincerest apologies for the delay. As you know, these source codes often deviate from their initial shape over time and need to be re-tested extensively, and coinciding with my vacation didn't exactly help in getting the code out soon.

That said, I've just added the python script for training and testing and added the instructions for doing so on the read me file. I'll leave the issue open for a few days in case any follow up questions come along. Let me know if you need anything else :)
