### ISSUE TITLE
couldn't install meta-dataset==0.2.0

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [peymanbateni/simple-cnaps#9]
Hi Thanks for writing this repo

I came across an error when installing the requirement list.
it says ERROR: No matching distribution found for meta-dataset==0.2.0

**Comment by peymanbateni** [comment]
Hi there,

Thanks a lot for your interest in our work :)

Yeah, the requirement file has a few additional dependencies that are not needed. We are preparing a major update to this repo with better code (and also code for our two follow-up codes). I'll see if we can push the cleaned-up requirements.txt file earlier. In the meantime, if you hit any errors on any of the requirements.txt entries, just remove that entry. The dependencies basically consist of those for the meta-dataset + pytorch, torchvision (and a few small ones that are easy to identify on the first run).

I'll send an update shortly addressing this fully. Let me know if you need any assistance in the meantime!

Thanks,
Peyman

**Comment by peymanbateni** [comment]
I'm going to close this issue now! Let me know if you experience any issues with getting the environments set up.
